#kitName
kit-ui-name: "Kit Selection"  # The name you want for your UI
kit-key: "SecredKey"
#database
mysql:
  host: localhost
  port: 3306
  database: minecraft
  username: admin
  password: Avrodite1!
