mysql:
  host: localhost
  port: 3306
  database: minecraft
  username: admin
  password: Avrodite1!
database:
  host: localhost
  port: 3306
  name: bravekitdb
  username: admin
  password: Avrodite1!