#kitName
kit-ui-name: "Kit Selection"  # The name you want for your UI
kit-key: "SecredKey"
#database
mysql:
  host: localhost
  port: 3306
  database: minecraft
  username: admin
  password: password
kits:
  1:
    name: "Starter Kit"
    description:
      - "This is the advanced kit."
      - "It includes powerful weapons and consumables."
    cooldown: 60 # Cooldown in seconds
    permission: "kits.starter"
    items:
      - material: DIAMOND_SWORD
        amount: 1
        enchantments:
          - type: DAMAGE_ALL
            level: 2
      - material: BREAD
        amount: 16
  2:
    name: "Advanced Kit"
    description:
      - "This is the advanced kit."
      - "It includes powerful weapons and consumables."
    cooldown: 120
    permission: "kits.advanced"
    items:
      - material: NETHERITE_SWORD
        amount: 1
        enchantments:
          - type: FIRE_ASPECT
            level: 1
      - material: GOLDEN_APPLE
        amount: 3
      - material: ARROW
        amount: 62
